### PR TITLE
Code cleanup

### LINKED ISSUE #117: Securing code and improving code quality - Ben's sections
# To be achieved this week:
- Secure all codes/commands (defensive programming to proactively catch bugs, input validation)
- Ensure coding conventions are followed
- Improve tests for each function
- Improve code quality: logging, exceptions, assertions
- SLAP

# The sections I will be cleaning up:
- note
- add patient
- help command
- AddressBookParser.java
- Note.java
- Tag.java
- DuplicatePatientException.java (model/patient/exception)
- PatientNoteFormatter.java
- AddressBookStorage.java
- JsonAdaptedNote.java
- JsonAdaptedPatient.java
- JsonAdaptedTag.java

### LINKED ISSUE #146: Filternote returns weird error message when given valid index and a title that doesn't exist -ben
When filtering notes for a valid index, if I give a title that doesn't exist the error message has the weird number thing of %1$% 
Image

### PR DESCRIPTION
**Pull request by benedictleejr**
# The sections cleaned up:
- Note.java
- NoteCommand.java
- NoteTest.java and NoteCommandTest.java
- JsonAdaptedNote.java
---
- Help Command
- Add patient command
- JsonAdaptedPatient.java
- JsonAdaptedTag.java
---
- Tag.java
- DuplicatePatientException.java (model/patient/exception)
- PatientNoteFormatter.java
---
- AddressBookParser.java
- AddressBookStorage.java

Resolves #146, #140, #162
Closes #117

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -193,9 +195,27 @@ public Optional<Address> getAddress() {
...
+         * Preserves the first occurrence of each unique tag name.
          */
         public void setTags(Set<Tag> tags) {
-            this.tags = (tags != null) ? new HashSet<>(tags) : null;
+            if (tags == null) {
+                this.tags = null;
+                return;
+            }
+
+            // Use a map to track tags by lowercase name for case-insensitive comparison
```
Comment (AndreChia) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:207]: Good catch by @Fieash so that we can fix duplicate tags before v1.5 to address #162

File: src/main/java/seedu/address/logic/commands/NoteCommand.java [hunk 2]
```diff
@@ -66,6 +65,12 @@ public CommandResult execute(Model model) throws CommandException {
 
         // Copy existing notes and add the new note
         TreeSet<Note> updatedNotes = new TreeSet<>(patientToEdit.getNotes());
+
+        // Not allowed to create notes with the same title
+        if (alreadyHasNoteTitle(updatedNotes, note)) {
```
Comment (AndreChia) [inline src/main/java/seedu/address/logic/commands/NoteCommand.java:70]: Nice bugfix that addresses many of our issues from alpha test

File: src/main/java/seedu/address/logic/commands/NoteCommand.java [hunk 3]
```diff
@@ -83,8 +88,30 @@ public CommandResult execute(Model model) throws CommandException {
...
-     * Stores the details to add the note with. Each non-empty field value will replace the
-     * corresponding field value of the note.
+     * Returns true if the note title already exists in the updated notes.
+     * Method is case-insensitive, meaning "Note" and "note" are considered the same.
+     *
+     * @param updatedNotes The updated notes of the patient.
+     * @param note The note to check for duplicates.
+     * @return true if the note title already exists, false otherwise.
+     */
+    public boolean alreadyHasNoteTitle(TreeSet<Note> updatedNotes, Note note) {
```
Comment (AndreChia) [inline src/main/java/seedu/address/logic/commands/NoteCommand.java:98]: Quick fix for now but a HashSet might be better to check for duplicates

File: src/test/java/seedu/address/logic/commands/EditCommandTest.java [hunk 4]
```diff
@@ -201,4 +205,48 @@ public void toStringMethod() {
         assertEquals(expected, editCommand.toString());
     }
 
+    @Test
```
Comment (AndreChia) [inline src/test/java/seedu/address/logic/commands/EditCommandTest.java:208]: Nice that you added test coverage for the newly added tag duplication checking functionality

File: src/test/java/seedu/address/logic/commands/NoteCommandTest.java [hunk 5]
```diff
@@ -52,4 +54,31 @@ public void equals() {
         assertFalse(standardCommand.equals(new NoteCommand(INDEX_FIRST_PATIENT,
                 new Note(VALID_NOTE_TITLE_BOB, VALID_NOTE_CONTENT_AMY))));
     }
+
+    @Test
```
Comment (AndreChia) [inline src/test/java/seedu/address/logic/commands/NoteCommandTest.java:58]: The test suite is well structured and features multiple cases while adhering to the guideline of having only one negative test case.

**Review by AndreChia — APPROVED** [review]
LGTM.
