### PR TITLE
Fix alpha bugs

### LINKED ISSUE #141: Can improve on error message
Can improve on the error message. Instead of just saying unknown command, we can consider to add more: Unknown command can refer to user guide for correct command keywords. 

Image

### PR DESCRIPTION
**Pull request by Golddirio**
I have fixed #141 #142 #143 
Also for #152 I perfect the message for invalid range.

### CODE REVIEW

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -13,18 +13,21 @@
...
+            + " to the User Guide for the correct command format! ";
     public static final String MESSAGE_INVALID_COMMAND_FORMAT = "Invalid command format! \n%1$s";
     public static final String MESSAGE_INVALID_PATIENT_DISPLAYED_INDEX = "The patient index provided is invalid";
     public static final String MESSAGE_INVALID_NOTE_DELETE_TITLE = "The note title provided is invalid";
     public static final String MESSAGE_PATIENTS_LISTED_OVERVIEW = "%1$d patients listed!";
     public static final String MESSAGE_DUPLICATE_FIELDS =
                 "Multiple values specified for the following single-valued field(s): ";
-    public static final String MESSAGE_DUPLICATE_PATIENT = "This patient already exists in the app";
+    public static final String MESSAGE_DUPLICATE_PATIENT = "This patient already exists in the app. Duplicate"
+            + " patient name is not allowed. ";
```
Comment (benedictleejr) [inline src/main/java/seedu/address/logic/Messages.java:25]: Good to make the error message explicit, so the user understands what the issue is

File: src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java [hunk 2]
```diff
@@ -27,7 +27,7 @@ public class DeleteNoteCommand extends Command {
     public static final String MESSAGE_USAGE = COMMAND_WORD
             + ": Deletes a specified note of a patient identified by the title string used "
             + "in the displayed note list.\n"
-            + "Parameters: INDEX (must be a positive integer) nt/TITLE (must be a valid string)\n"
+            + "Parameters: INDEX (must be a positive integer) nt/[NOTE TITLE] (must be a valid string)\n"
```
Comment (benedictleejr) [inline src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java:30]: Good to ensure formatting consistency

**Review by benedictleejr — APPROVED** [review]
LGTM!

**Review by danplatypus30 — APPROVED** [review]
LGTM

**Review by Fieash — APPROVED** [review]
